package ca.chisel.interview;



import com.github.javafaker.Faker;

import java.util.Objects;
import java.util.UUID;

/**
 * A POJO for Keys and Values to be generated by EasyRandom
 */
public class KeyValueObject {
    private final String key;
    private final String value;

    public KeyValueObject() {
        this.key = UUID.randomUUID().toString();
        this.value = Faker.instance().name().fullName();
    }

    public String getKey() {
        return key;
    }

    public String getValue() {
        return value;
    }


    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        final KeyValueObject that = (KeyValueObject) o;
        return key.equals(that.key) && value.equals(that.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(key, value);
    }
}
